
import 'package:grekino/models/great_movie_model.dart';

final List<GreatMovieModel> localGreatMovies = [
  GreatMovieModel(
      id: "55317353-e061-4307-ac9c-131633fffcfe",
      name: "Paper Moon",
      director: "Peter Bogdanovich",
      volume: 1,
      year: 1973,
      genres: ["drama", "crime"],
      description: "",
      imdbId: "0118884",
      posterImageUrl: "",
      isCriterion: false,
      isWatched: false,
      dateWatched: "1990-07-07",
      userStarRating: 0.0,
      userReview: "",
      isSynced: false),
  GreatMovieModel(
      id: "6d435909-b3aa-4192-9c1f-423741fa83c0",
      name: "The Godfather",
      director: "Francis Ford Coppola",
      volume: 1,
      year: 1974,
      genres: ["drama", "crime"],
      description: "",
      imdbId: "0118856",
      posterImageUrl: "",
      isCriterion: false,
      isWatched: false,
      dateWatched: "1990-07-07",
      userStarRating: 0.0,
      userReview: "",
      isSynced: false),
];

final List<GreatMovieModel> firestoreGreatMovies = [
  GreatMovieModel(
      id: "46ac86d5-038b-4225-9096-fe7946a341ad",
      name: "Roadhouse",
      director: "Rowdy Herrington",
      volume: 1,
      year: 1989,
      genres: ["comedy", "crime"],
      description: "",
      imdbId: "0118878",
      posterImageUrl: "",
      isCriterion: false,
      isWatched: false,
      dateWatched: "1990-07-07",
      userStarRating: 0.0,
      userReview: "",
      isSynced: false),
  GreatMovieModel(
      id: "aef23b38-b583-47fe-aee9-09a9cfedf548",
      name: "Point Break",
      director: "Kathryn Bigelow",
      volume: 1,
      year: 1990,
      genres: ["drama", "crime"],
      description: "",
      imdbId: "0555555",
      posterImageUrl: "",
      isCriterion: false,
      isWatched: false,
      dateWatched: "1990-07-07",
      userStarRating: 0.0,
      userReview: "",
      isSynced: false),
];