// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbpJA3keTvM98FJ4DJjBSZhOvBzsJ0T_8',
    appId: '1:759334845954:web:4a3fc31a6817449b2b311b',
    messagingSenderId: '759334845954',
    projectId: 'grekino-d8ac5',
    authDomain: 'grekino-d8ac5.firebaseapp.com',
    storageBucket: 'grekino-d8ac5.appspot.com',
    measurementId: 'G-HG9QS028ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxf8X5UsSCUurXYNkz4pxaQXcAWPiGxLE',
    appId: '1:759334845954:android:19cbd9bb6f2ce40c2b311b',
    messagingSenderId: '759334845954',
    projectId: 'grekino-d8ac5',
    storageBucket: 'grekino-d8ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV7XU81lMOHyHgWbpltqYNNMzV62nOjGU',
    appId: '1:759334845954:ios:827ca2e1e90ef82c2b311b',
    messagingSenderId: '759334845954',
    projectId: 'grekino-d8ac5',
    storageBucket: 'grekino-d8ac5.appspot.com',
    iosBundleId: 'com.sparkwing.grekino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV7XU81lMOHyHgWbpltqYNNMzV62nOjGU',
    appId: '1:759334845954:ios:efe76434564ea67b2b311b',
    messagingSenderId: '759334845954',
    projectId: 'grekino-d8ac5',
    storageBucket: 'grekino-d8ac5.appspot.com',
    iosBundleId: 'com.sparkwing.grekino.RunnerTests',
  );
}
