// Mocks generated by Mockito 5.4.4 from annotations
// in grekino/test/views/movie_list_item_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i5;

import 'package:grekino/providers/i_great_movies_provider.dart' as _i2;
import 'package:grekino/view_models/movie_list_item_view_model.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIGreatMoviesProvider_0 extends _i1.SmartFake
    implements _i2.IGreatMoviesProvider {
  _FakeIGreatMoviesProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieListItemViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListItemViewModel extends _i1.Mock
    implements _i3.MovieListItemViewModel {
  @override
  _i2.IGreatMoviesProvider get greatMoviesProvider => (super.noSuchMethod(
        Invocation.getter(#greatMoviesProvider),
        returnValue: _FakeIGreatMoviesProvider_0(
          this,
          Invocation.getter(#greatMoviesProvider),
        ),
        returnValueForMissingStub: _FakeIGreatMoviesProvider_0(
          this,
          Invocation.getter(#greatMoviesProvider),
        ),
      ) as _i2.IGreatMoviesProvider);

  @override
  set greatMoviesProvider(_i2.IGreatMoviesProvider? _greatMoviesProvider) =>
      super.noSuchMethod(
        Invocation.setter(
          #greatMoviesProvider,
          _greatMoviesProvider,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get loading => (super.noSuchMethod(
        Invocation.getter(#loading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get posterImageUrl => (super.noSuchMethod(
        Invocation.getter(#posterImageUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#posterImageUrl),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#posterImageUrl),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  dynamic setLoading(bool? loading) => super.noSuchMethod(
        Invocation.method(
          #setLoading,
          [loading],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic setPosterImageUrl(String? url) => super.noSuchMethod(
        Invocation.method(
          #setPosterImageUrl,
          [url],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic setDescription(String? overview) => super.noSuchMethod(
        Invocation.method(
          #setDescription,
          [overview],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
